### ISSUE TITLE
Inputting Thermal Boundary Conditions

### ISSUE THREAD

**Issue by suzaku9** [jcanton/pipeMeshNek#1]
I' found this code quite useful, both for creating and visualizing meshes. I had a small  query, over how to have the thermal boundary conditions incorporated into the rea file in case heat transfer is required for the problem. Does the code need to be modified in some shape or form?

**Comment by jcanton** [comment]
Hi Suzaku,
Thank you for your comment. I never worked with heat transfer in nek5000, but yes: in order to have the boundary conditions in the rea file you would need to modify the code, feel free to do so!
