### ISSUE TITLE
The current included INPUTgeometry file doesn't include the pipeBC and errors out.

### ISSUE THREAD

**Issue by lcarasik** [jcanton/pipeMeshNek#3]
The current INPUTgeometry file included with master doesn't include the pipeBC input above the Re input. 

It causes the following error:

```
At line 117 of file pipeMeshNek.f90 (unit = 100, file = 'INPUTgeometry')
Fortran runtime error: Bad integer for item 1 in list input

Error termination. Backtrace:
#0  0x7f2f3a2372da in ???
#1  0x7f2f3a237ec5 in ???
#2  0x7f2f3a23868d in ???
#3  0x7f2f3a3a4924 in ???
#4  0x7f2f3a3a7c1a in ???
#5  0x7f2f3a3a90f9 in ???
#6  0x562b63c62e0d in pipemeshnek
	at /home/lanecarasik/projects/pipeMeshNek/pipeMeshNek.f90:117
#7  0x562b63c6bbbd in main
	at /home/lanecarasik/projects/pipeMeshNek/pipeMeshNek.f90:1096
```

Fixed it by adding IO above the line 

```
10.    # Re
```

Is this a known issue?

**Comment by jcanton** [comment]
Dear Lane,
thank you for pointing this out, I forgot to update the example INPUTgeometry.
As you may imagine, this was only a repository for my convenience, not meant for "public" use.
Feel free to use it (I'm happy if you do) but please note that the mesh quality could be greately improved on the section of the pipe, so I would recommend not using it for "production runs" but only for testing.

Best,
Jacopo

**Comment by lcarasik** [comment]
Hey Jacopo,

The script was certainly helpful so I could get reacquainted with Nek5000. 

Thanks for putting it up on git hub and I understand about not using it for production runs in it's current state.

Thanks,

Lane
